fix: build with stylesheets

diff --git a/.github/workflows/docs-build.yml b/.github/workflows/docs-build.yml
--- a/.github/workflows/docs-build.yml
+++ b/.github/workflows/docs-build.yml
@@ -28,29 +28,29 @@ jobs:
           ref: main
           path: main-config
 
-      - name: Sync workflow file to cells-v4 and cells-v5
-        if: github.ref_name == 'main' && contains(github.event.commits.*.added, '.github/workflows/build-docs.yaml') || contains(github.event.commits.*.modified, '.github/workflows/build-docs.yaml')
-        run: |
-          git config user.name "GitHub Action"
-          git config user.email "action@github.com"
-          for branch in cells-v4 cells-v5 pydio-v8; do
-            git checkout $branch || git checkout -b $branch
-            mkdir -p .github/workflows
-            cp .github/workflows/build-docs.yaml .github/workflows/
-            git add .github/workflows/build-docs.yaml
-            git commit -m "Sync build-docs.yaml from main to $branch" || echo "No changes to commit"
-            git push origin $branch
-          done
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Sync workflow file to cells-v4 and cells-v5
+      #   if: github.ref_name == 'main' && contains(github.event.commits.*.added, '.github/workflows/build-docs.yaml') || contains(github.event.commits.*.modified, '.github/workflows/build-docs.yaml')
+      #   run: |
+      #     git config user.name "GitHub Action"
+      #     git config user.email "action@github.com"
+      #     for branch in cells-v4 cells-v5 pydio-v8; do
+      #       git checkout $branch || git checkout -b $branch
+      #       mkdir -p .github/workflows
+      #       cp .github/workflows/build-docs.yaml .github/workflows/
+      #       git add .github/workflows/build-docs.yaml
+      #       git commit -m "Sync build-docs.yaml from main to $branch" || echo "No changes to commit"
+      #       git push origin $branch
+      #     done
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Copy config and resources from main
         run: |
           cp main-config/mkdocs.yml .
           cp main-config/requirements.txt .
           mkdir -p resources docs overrides
-          cp main-config/resources/* resources/ || echo "resources not found"
-          cp main-config/overrides/* overrides/ || echo "404.html not found"
+          cp -r main-config/resources/* resources/ || echo "resources not found"
+          cp -r main-config/overrides/* overrides/ || echo "404.html not found"
           cp -r main-config/tools .
           rm -rf main-config
 
